/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Time,
  'gamePayload' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'getConversationHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [Message], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Time,
    'gamePayload' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'getConversationHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text], [Message], []),
  });
};

export const init = ({ IDL }) => { return []; };